
services: 
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password  
      MONGO_INITDB_DATABASE: CheckmarkBackend  
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db  
  
volumes:
  mongodb_data:
