
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongodb:27017/CheckmarkBackend  # Use service name
    ports:
      - "3000:3000"
    env_file:
      - .env.production 
    depends_on:
      - mongodb  # Ensure MongoDB container starts before the server
  
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password  # Specify your MongoDB password here
      MONGO_INITDB_DATABASE: CheckmarkBackend  # Updated database name
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db  # Persist MongoDB data
  
volumes:
  mongodb_data:
